version: "3"

services:
  app:
    image: ${DTR_URL}/demo/docker-demo:${TAG}
    deploy:
      mode: replicated
      replicas: 4
      update_config:
        parallelism: 2
        delay: 5s
        failure_action: continue
      labels:
        - "com.docker.ucp.mesh.http.8080=internal_port=8080,external_route=http://docker-demo-${ENVIRONMENT}.${DOMAIN_NAME}"
        - "com.docker.ucp.access.label=${COMPOSE_PROJECT}"
    entrypoint: /bin/sh
    command: -c "sleep 5 && go-wrapper run"
    environment:
      - "TITLE=Docker Demo-${ENVIRONMENT}"
      - "DB_HOST=db"
      - "DB_PORT=5432"
      - "DB_USER=${DB_USER}"
      - "DB_PASS=${DB_PASS}"
      - "DB_NAME=${DB_NAME}"
      - "DB_SSL_MODE=disable"
    networks:
      - docker-demo
      - ucp-hrm
    ports:
      - "8080"
  db:
    image: ${DTR_URL}/official/postgres:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.role == manager"
      labels:
        - "com.docker.ucp.access.label=${COMPOSE_PROJECT}"
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASS}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - docker-demo

volumes:
  postgres-data:
    driver: local

networks:
  docker-demo:
    driver: overlay
  ucp-hrm:
    external: true
